version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    container_name: ${IMAGE_NAME}
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${IMAGE_NAME}
      SERVICE_TAGS: dev
    volumes:
      - ./.env:/var/www/.env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bisindo.rule=Host(`card-bisindo.${APP_HOST}`)"
      - "traefik.http.routers.bisindo.entrypoints=web"
      - "traefik.http.middlewares.bisindo-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bisindo.middlewares=bisindo-https-redirect"
      - "traefik.http.routers.bisindo-secure.rule=Host(`card-bisindo.${APP_HOST}`)"
      - "traefik.http.routers.bisindo-secure.entrypoints=websecure"
      - "traefik.http.routers.bisindo-secure.tls=true"
      - "traefik.http.routers.bisindo-secure.tls.certresolver=http"
      - "traefik.http.routers.bisindo-secure.service=bisindo"
      - "traefik.http.services.bisindo.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"

    networks:
      - database-network
      - proxy

networks:
  database-network:
    external: true
  proxy:
    external: true

